
[{ _index: 'movies',
    _type: 'all',
    _id: 'tt0111488',
    _score: 1,
    _source:
     { adult: 'False',
       belongs_to_collection: '',
       budget: '0',
       genres: [Array],
       homepage: '',
       id: '41590',
       imdb_id: 'tt0111488',
       original_language: 'en',
       original_title: 'Trial by Jury',
       overview:
        'Valerie is a juror in the trail of a mob boss. When her young son\'s life is threatened, she has no option other than to see that justice isn\'t done.',
       popularity: '0.85586',
       poster_path: '/qv6iQOtIbktcUZcE7VIoComjtMI.jpg',
       production_companies: [Array],
       production_countries: [Array],
       release_date: '1994-09-09',
       revenue: 0,
       runtime: 107,
       spoken_languages: [Array],
       status: 'Released',
       tagline:
        'For one juror, the question of guilt or innocence is a matter of life or death... her own.',
       title: 'Trial by Jury',
       video: false,
       vote_average: 5.5,
       vote_count: 5,
       poster:
        'https://m.media-amazon.com/images/M/MV5BMjgyMjYxYzMtOTY4Zi00ZjYxLThkNmEtZmY1NWExZDJjMWU3XkEyXkFqcGdeQXVyNzc5MjA3OA@@._V1_SX300.jpg',
       categories: 'Thriller, Crime, Drama',
       actors:
        'Joanne Whalley, Armand Assante, Gabriel Byrne, William Hurt',
       director: 'Heywood Gould',
       language: 'English',
       production: 'Warner Home Video' } },
  { _index: 'movies',
    _type: 'all',
    _id: 'tt0102855',
    _score: 1,
    _source:
     { adult: 'False',
       belongs_to_collection: '',
       budget: '0',
       genres: [Array],
       homepage: '',
       id: '88893',
       imdb_id: 'tt0102855',
       original_language: 'de',
       original_title: 'Schrei aus Stein',
       overview:
        'A meeting of two world famous climbers, one an experienced mountaineer the other a sport climber, and a journalist (Ivan) results in a bet on which of the two is the best climber. Roger (the mountaineering expert) states that Martin (the sport climber) wouldn\'t survive a day on a \'real\' climbing expedition, although he is considered to be the world\'s best sport climber (having just won an indoor \'world championship,\' an event depicted in the opening scene). They plan to climb \'Cerro Torre,\' in the Patagonia region of South America, near the Argentinian/Chilean border, one of the world\'s most difficult mountains, especially considering the extreme weather conditions common to the area.',
       popularity: '0.736081',
       poster_path: '/459MeLTQMF9hlNvaHbUuBPIo5I6.jpg',
       production_companies: [],
       production_countries: [],
       release_date: '1991-01-01',
       revenue: 0,
       runtime: 105,
       spoken_languages: [Array],
       status: 'Released',
       tagline: 'In this battle, there can be no winners',
       title: 'Scream of Stone',
       video: false,
       vote_average: 7.5,
       vote_count: 4,
       poster:
        'https://images-na.ssl-images-amazon.com/images/M/MV5BMjkwNDEyODY4OF5BMl5BanBnXkFtZTcwODQyNjUyMQ@@._V1_SX300.jpg',
       categories: 'Drama',
       actors:
        'Vittorio Mezzogiorno, Stefan Glowacz, Mathilda May, Al Waxman',
       director: 'Werner Herzog',
       language: 'English, Spanish',
       production: 'Alliance' } },
  { _index: 'movies',
    _type: 'all',
    _id: 'tt0114658',
    _score: 1,
    _source:
     { adult: 'False',
       belongs_to_collection: '',
       budget: '33500000',
       genres: [Array],
       homepage: '',
       id: '36259',
       imdb_id: 'tt0114658',
       original_language: 'en',
       original_title: 'Theodore Rex',
       overview:
        'In an alternate futuristic society, a tough female police detective is paired with a talking dinosaur to find the killer of dinosaurs and other prehistoric animals leading them to a mad scientist bent on creating a new Armageddon.',
       popularity: '2.583686',
       poster_path: '/aQhmZkynXG7Gu3YGSmF9k2skL3W.jpg',
       production_companies: [Array],
       production_countries: [Array],
       release_date: '1995-12-14',
       revenue: 0,
       runtime: 92,
       spoken_languages: [Array],
       status: 'Released',
       tagline:
        'The world\'s toughest cop is getting a brand new partner. And he\'s a real blast from the past!',
       title: 'Theodore Rex',
       video: false,
       vote_average: 3.6,
       vote_count: 17,
       poster:
        'https://images-na.ssl-images-amazon.com/images/M/MV5BMGE2MDBhODctN2JhMy00NGRjLWFlZjAtNjk5MGUwNTBmMzJlXkEyXkFqcGdeQXVyMTQ2MjQyNDc@._V1_SX300.jpg',
       categories: 'Action, Comedy, Family',
       actors:
        'Whoopi Goldberg, Armin Mueller-Stahl, Juliet Landau, Bud Cort',
       director: 'Jonathan R. Betuel',
       language: 'English',
       production: 'New Line Cinema' } },
  { _index: 'movies',
    _type: 'all',
    _id: 'tt0111709',
    _score: 1,
    _source:
     { adult: 'False',
       belongs_to_collection: '',
       budget: '0',
       genres: [Array],
       homepage: '',
       id: '53185',
       imdb_id: 'tt0111709',
       original_language: 'en',
       original_title: 'Wide Eyed and Legless',
       overview:
        'Diana and Deric have an ideal marriage: they thrive in each other\'s company, they\'re funny, and they enjoy their two grown children and Deric\'s dotty mother; the trouble is, Diana can no longer walk and her malady defies medical diagnosis. To care for Diana, Deric is letting his business slide, but at a civic luncheon, he is seated next to Aileen Armitage, a novelist who is blind. They have a nice time, and on the sly, Diana contacts Aileen to made an odd request. Diana\'s declining health and her resolve bring this triangle of unlikely friends to a surprising place.',
       popularity: '0.00015',
       poster_path: '/iP2WwrkkdZPN34y7phWTJx9N3LE.jpg',
       production_companies: [],
       production_countries: [],
       release_date: '1993-09-05',
       revenue: 0,
       runtime: 102,
       spoken_languages: [Array],
       status: 'Released',
       tagline: '',
       title: 'Wide Eyed and Legless',
       video: false,
       vote_average: 0,
       vote_count: 0,
       poster:
        'https://images-na.ssl-images-amazon.com/images/M/MV5BNTA0MTExMDY1NF5BMl5BanBnXkFtZTcwMzI4MjkxMQ@@._V1_SX300.jpg',
       categories: 'Comedy, Crime, Drama',
       actors: 'Julie Walters, Jim Broadbent, Thora Hird, Sian Thomas',
       director: 'Richard Loncraine',
       language: 'English' } },
  { _index: 'movies',
    _type: 'all',
    _id: 'tt0073778',
    _score: 1,
    _source:
     { adult: 'False',
       belongs_to_collection: '',
       budget: '0',
       genres: [Array],
       homepage: '',
       id: '52633',
       imdb_id: 'tt0073778',
       original_language: 'en',
       original_title: 'Switchblade Sisters',
       overview:
        'A tough gang of teenage girls are looking for love and fighting for turf on the mean streets of the city! Bad girls to the core, these impossibly outrageoushigh school hoodlums go where they want ... and create mayhem wherever they go!',
       popularity: '6.035166',
       poster_path: '/sEYeoOBXAllmHynCNrNBEJjratp.jpg',
       production_companies: [Array],
       production_countries: [Array],
       release_date: '1975-01-05',
       revenue: 0,
       runtime: 91,
       spoken_languages: [Array],
       status: 'Released',
       tagline: 'So Easy to Kill, So Hard to Love',
       title: 'Switchblade Sisters',
       video: false,
       vote_average: 6.6,
       vote_count: 27,
       poster:
        'https://m.media-amazon.com/images/M/MV5BYmI0NzIzMDItMTkxYy00NzJjLWI0OGUtZGQ4ODI5YzVjNzExL2ltYWdlXkEyXkFqcGdeQXVyNzc5MjA3OA@@._V1_SX300.jpg',
       categories: 'Action, Crime, Drama',
       actors: 'Robbie Lee, Joanne Nail, Monica Gayle, Asher Brauner',
       director: 'Jack Hill',
       language: 'English',
       production: 'Rolling Thunder Pictures' } },
  { _index: 'movies',
    _type: 'all',
    _id: 'tt0113083',
    _score: 1,
    _source:
     { adult: 'False',
       belongs_to_collection: '',
       budget: '0',
       genres: [Array],
       homepage: '',
       id: '4307',
       imdb_id: 'tt0113083',
       original_language: 'es',
       original_title: 'La flor de mi secreto',
       overview:
        'Marisa Paredes is Leocadia ("Leo") Macias, a woman writing “pink” romance novels under the alias of Amanda Gris that are very popular all across Spain. Unlike her romantic novels, her own love life is troubled. Leo has a less than happy relationship with her husband Paco, a military officer stationed in Brussels then later in Bosnia, who is distant both physically and emotionally.',
       popularity: '2.286788',
       poster_path: '/ssWPuAaSbIwWczkKAfvk2hTAVoX.jpg',
       production_companies: [Array],
       production_countries: [Array],
       release_date: '1995-09-22',
       revenue: 0,
       runtime: 107,
       spoken_languages: [Array],
       status: 'Released',
       tagline: 'Every woman has a secret...',
       title: 'The Flower of My Secret',
       video: false,
       vote_average: 6.9,
       vote_count: 43,
       poster:
        'https://m.media-amazon.com/images/M/MV5BMjAxMTM1OTQ3MV5BMl5BanBnXkFtZTcwNjQ1MzgyMQ@@._V1_SX300.jpg',
       categories: 'Drama',
       actors: 'Marisa Paredes, Juan Echanove, Carme Elias, Rossy de Palma',
       director: 'Pedro Almodóvar',
       language: 'Spanish, French',
       production: 'Sony Pictures Classics' } },
  { _index: 'movies',
    _type: 'all',
    _id: 'tt0117104',
    _score: 1,
    _source:
     { adult: 'False',
       belongs_to_collection: '',
       budget: '25000000',
       genres: [Array],
       homepage: '',
       id: '40001',
       imdb_id: 'tt0117104',
       original_language: 'en',
       original_title: 'Mrs. Winterbourne',
       overview:
        'Connie Doyle is eighteen and pregnant her boyfriend has kicked her out. She accidentaly ends up on a train where she meets Hugh Winterbourne and his wife Patricia who is pregnant. The train wrecks and she wakes up in the hosptial to find out that it\'s been assumed that she\'s Patricia. Hugh\'s mother takes her in and she falls in love with Hugh\'s brother Bill. Just when she thinks everything is going her way, her ex-boyfriend shows up.',
       popularity: '9.1861',
       poster_path: '/4XNWsXCv7vY04RzxyUrN7zWHlxU.jpg',
       production_companies: [Array],
       production_countries: [Array],
       release_date: '1996-04-19',
       revenue: 10070000,
       runtime: 105,
       spoken_languages: [Array],
       status: 'Released',
       tagline: 'The story of a girl who is going from filthy to rich',
       title: 'Mrs. Winterbourne',
       video: false,
       vote_average: 5.5,
       vote_count: 26,
       poster:
        'https://m.media-amazon.com/images/M/MV5BNjg3Mzg5Y2UtNzQ5Yy00NGY4LTk5M2QtZGE1NmZkZTBlZmEwXkEyXkFqcGdeQXVyNzc5MjA3OA@@._V1_SX300.jpg',
       categories: 'Comedy, Drama, Romance',
       actors:
        'Shirley MacLaine, Ricki Lake, Brendan Fraser, Miguel Sandoval',
       director: 'Richard Benjamin',
       language: 'English',
       production: 'Sony Pictures Home Entertainment' } },
  { _index: 'movies',
    _type: 'all',
    _id: 'tt0117312',
    _score: 1,
    _source:
     { adult: 'False',
       belongs_to_collection: '',
       budget: '0',
       genres: [Array],
       homepage: '',
       id: '287305',
       imdb_id: 'tt0117312',
       original_language: 'de',
       original_title: 'Peanuts – Die Bank zahlt alles',
       overview: '',
       popularity: '0.066123',
       poster_path: '/wpk30SvRHmjC2plgKHZXxG0FlKd.jpg',
       production_companies: [Array],
       production_countries: [Array],
       release_date: '1996-03-21',
       revenue: 0,
       runtime: null,
       spoken_languages: [],
       status: 'Released',
       tagline: '',
       title: 'Peanuts – Die Bank zahlt alles',
       video: false,
       vote_average: 4,
       vote_count: 1,
       poster:
        'https://images-na.ssl-images-amazon.com/images/M/MV5BMzE5MzY1ODQ0MV5BMl5BanBnXkFtZTcwMzY3NDgxMQ@@._V1_SX300.jpg',
       categories: 'Comedy',
       actors: 'Ulrich Mühe, Iris Berben, Marita Marschall, Rufus Beck',
       director: 'Carlo Rola',
       language: 'German',
       production: 'N/A' } },
  { _index: 'movies',
    _type: 'all',
    _id: 'tt0116448',
    _score: 1,
    _source:
     { adult: 'False',
       belongs_to_collection: '',
       budget: '0',
       genres: [Array],
       homepage: '',
       id: '20759',
       imdb_id: 'tt0116448',
       original_language: 'en',
       original_title: 'The Great White Hype',
       overview:
        'When the champ\'s promoter, Rev. Sultan, decides something new is needed to boost the marketability of the boxing matches, he searches and finds the only man to ever beat the champ. The problem is that he isn\'t a boxer anymore and he\'s white. However, once Rev. Sultan convinces him to fight, he goes into heavy training
while the confident champ takes it easy and falls out of shape.',
       popularity: '3.321765',
       poster_path: '/15x1IKSbzO3qX4191Wf9UpuwK8D.jpg',
       production_companies: [Array],
       production_countries: [Array],
       release_date: '1996-05-03',
       revenue: 0,
       runtime: 91,
       spoken_languages: [Array],
       status: 'Released',
       tagline: 'If you can\'t find the perfect contender....make one.',
       title: 'The Great White Hype',
       video: false,
       vote_average: 5.1,
       vote_count: 29,
       poster:
        'https://m.media-amazon.com/images/M/MV5BZmQ0NGE0MGUtZTNjMi00N2EyLThkMDUtZDg0NzIzNmUxNzc5XkEyXkFqcGdeQXVyNzc5MjA3OA@@._V1_SX300.jpg',
       categories: 'Comedy, Sport',
       actors:
        'Samuel L. Jackson, Jeff Goldblum, Peter Berg, Corbin Bernsen',
       director: 'Reginald Hudlin',
       language: 'English',
       production: 'Twentieth Century Fox Home Entertainment' } },
  { _index: 'movies',
    _type: 'all',
    _id: 'tt0110657',
    _score: 1,
    _source:
     { adult: 'False',
       belongs_to_collection:
        '{"id": 8580, "name": "The Karate Kid Collection", "poster_path": "/o6h2F0C5eZOy50Q76fNYzc9mvvw.jpg", "backdrop_path": "/1ok5JGCsDt4Sh3CkFeXh2F2KB7F.jpg"}',
       budget: '12000000',
       genres: [Array],
       homepage: '',
       id: '11231',
       imdb_id: 'tt0110657',
       original_language: 'en',
       original_title: 'The Next Karate Kid',
       overview:
        'During a commemoration for Japanese soldiers fighting in the US Army during World War II, Mr. Miyagi meets the widow of his commanding officer. He gets to know her granddaughter Julie, an angry teenager who is still feeling the pain of losing both her parents in an accident and is having problems with her grandmother and
her fellow pupils. Mr. Miyagi decides to teach her karate to get her through her pain and issues and back on the right path.',
       popularity: '9.9697',
       poster_path: '/gu5SOBWsoxDy6mWKAkOt20zTXOb.jpg',
       production_companies: [Array],
       production_countries: [Array],
       release_date: '1994-07-18',
       revenue: 15826984,
       runtime: 107,
       spoken_languages: [Array],
       status: 'Released',
       tagline: 'Who says the good guy has to be a guy?',
       title: 'The Next Karate Kid',
       video: false,
       vote_average: 4.8,
       vote_count: 202,
       poster:
        'https://m.media-amazon.com/images/M/MV5BYzQwOTVkZmQtMDMwNS00ZTQzLTlkODUtOWI0NDZkMjYxNWUwXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg',
       categories: 'Action, Drama, Family, Romance, Sport',
       actors:
        'Pat Morita, Hilary Swank, Michael Ironside, Constance Towers',
       director: 'Christopher Cain',
       language: 'English',
       production: 'Sony Pictures Home Entertainment' } },
  { _index: 'movies',
    _type: 'all',
    _id: 'tt0111252',
    _score: 1,
    _source:
     { adult: 'False',
       belongs_to_collection: '',
       budget: '200000',
       genres: [Array],
       homepage: '',
       id: '17600',
       imdb_id: 'tt0111252',
       original_language: 'en',
       original_title: 'Spanking the Monkey',
       overview:
        'Bright young student Raymond Aibelli is forced to sidetrack an important medical internship because his mother, Susan, is recovering from a broken leg. When
he isn\'t tasked with the most mundane aspects of Susan\'s recuperation, Raymond finds distraction in a neighborhood girl, Toni Peck. But, as Susan begins relying on
her son for both physical and emotional needs, Raymond starts developing disturbing and unwanted new yearnings.',
       popularity: '2.799575',
       poster_path: '/nr3KNkAu7tmiaBnNgxabrcyCLX0.jpg',
       production_companies: [Array],
       production_countries: [Array],
       release_date: '1994-01-15',
       revenue: 0,
       runtime: 106,
       spoken_languages: [Array],
       status: 'Released',
       tagline: 'A gripping comedy about letting go.',
       title: 'Spanking the Monkey',
       video: false,
       vote_average: 5.3,
       vote_count: 29,
       poster:
        'https://m.media-amazon.com/images/M/MV5BMjE5NTA0MDc0Ml5BMl5BanBnXkFtZTcwMTQ4MjYzMQ@@._V1_SX300.jpg',
       categories: 'Comedy, Drama',
       actors:
        'Jeremy Davies, Elizabeth Newett, Benjamin Hendrickson, Alberta Watson',
       director: 'David O. Russell',
       language: 'English',
       production: 'Sony Pictures Home Entertainment' } },
  { _index: 'movies',
    _type: 'all',
    _id: 'tt0108500',
    _score: 1,
    _source:
     { adult: 'False',
       belongs_to_collection:
        '{"id": 52888, "name": "The Visitors Collection", "poster_path": "/tqLSEkKYdkFCqsNHP1v9pnr0sl.jpg", "backdrop_path": "/ywYnkeaa7LZBU1bW8zavPwzve4X.jpg"}',
       budget: '0',
       genres: [Array],
       homepage: '',
       id: '11687',
       imdb_id: 'tt0108500',
       original_language: 'fr',
       original_title: 'Les visiteurs',
       overview:
        'This outrageous time-travel comedy follows the misadventures of a wacky medieval knight (Jean Reno) and his faithful servant when they are accidentally transported to contemporary times by a senile sorcererMayhem rules as these 12th-century visitors try adapting to the wildly confusing modern world. To avoid being stuck here for good, however, they soon begin an all-out cosmic assault on their former castle -- now a luxury hotel -- in their quest to return to the past',
       popularity: '7.326169',
       poster_path: '/tKCeoKQzf5kwaAMBkfhLyphuJeL.jpg',
       production_companies: [Array],
       production_countries: [Array],
       release_date: '1993-01-27',
       revenue: 0,
       runtime: 107,
       spoken_languages: [Array],
       status: 'Released',
       tagline: 'They Weren\'t Born Yesterday!',
       title: 'The Visitors',
       video: false,
       vote_average: 7.1,
       vote_count: 433,
       poster:
        'https://m.media-amazon.com/images/M/MV5BMjc2ODE2OTYtNTgyMS00ZDY1LWJiZjMtNzAxODcyN2VjZjhkXkEyXkFqcGdeQXVyMTY5MDE5NA@@._V1_SX300.jpg',
       categories: 'Comedy, Fantasy',
       actors:
        'Christian Clavier, Jean Reno, Valérie Lemercier, Marie-Anne Chazel',
       director: 'Jean-Marie Poiré',
       language: 'French, German, English',
       production: 'Gaumont' } },
  { _index: 'movies',
    _type: 'all',
    _id: 'tt0109593',
    _score: 1,
    _source:
     { adult: 'False',
       belongs_to_collection: '',
       budget: '0',
       genres: [Array],
       homepage: '',
       id: '38867',
       imdb_id: 'tt0109593',
       original_language: 'en',
       original_title: 'Delta of Venus',
       overview:
        'A struggling American writer and a fellow American expatriate begin a sordid affair among the chaos and discord of 1940 Paris, France on the brink of World War II.',
       popularity: '1.099187',
       poster_path: '/tV3GHas7BjqjNB6ta4SvL4TS6fv.jpg',
       production_companies: [Array],
       production_countries: [Array],
       release_date: '1995-06-09',
       revenue: 62949,
       runtime: 99,
       spoken_languages: [Array],
       status: 'Released',
       tagline:
        'In 1939, Elena went to Paris searching for her voice as a writer. What she found was her voice as a woman.',
       title: 'Delta of Venus',
       video: false,
       vote_average: 3.3,
       vote_count: 5,
       poster:
        'https://m.media-amazon.com/images/M/MV5BNDY0MGI3N2QtYTczNS00YTI5LWE2ZjAtNTY4MWJmZjdhMTRlXkEyXkFqcGdeQXVyMzM4MjM0Nzg@._V1_SX300.jpg',
       categories: 'Drama',
       actors: 'Audie England, Costas Mandylor, Eric da Silva, Raven Snow',
       director: 'Zalman King',
       language: 'English',
       production: 'New Line Home Entertainment' } },
  { _index: 'movies',
    _type: 'all',
    _id: 'tt0110366',
    _score: 1,
    _source:
     { adult: 'False',
       belongs_to_collection: '',
       budget: '0',
       genres: [Array],
       homepage: '',
       id: '10897',
       imdb_id: 'tt0110366',
       original_language: 'en',
       original_title: 'The Little Rascals',
       overview:
        'Spanky, Alfalfa, Buckwheat, and the other characters made famous in the Our Gang shorts of the 1920s and 1930s are brought back to life in this nostalgic children\'s comedy. When Alfalfa starts to question his devotion to the club\'s principles after falling for the beautiful nine-year old Darla, the rest of the gang sets out to keep them apart.',
       popularity: '6.707109',
       poster_path: '/bYpc0diOR3nk9yZeDXEHmsjuKjI.jpg',
       production_companies: [Array],
       production_countries: [Array],
       release_date: '1994-08-05',
       revenue: 67308282,
       runtime: 82,
       spoken_languages: [Array],
       status: 'Released',
       tagline: 'Mischief loves company',
       title: 'The Little Rascals',
       video: false,
       vote_average: 6.3,
       vote_count: 214,
       poster:
        'https://m.media-amazon.com/images/M/MV5BYWE1MzdmNmMtNWQwZS00MTVkLTk3MDMtYzVkOWZlOTczMDIwXkEyXkFqcGdeQXVyNjg4NzYzMzA@._V1_SX300.jpg',
       categories: 'Comedy, Family, Romance',
       actors:
        'Travis Tedford, Kevin Jamal Woods, Jordan Warkol, Zachary Mabry',
       director: 'Penelope Spheeris',
       language: 'English',
       production: 'MCA Universal Home Video' } },
  { _index: 'movies',
    _type: 'all',
    _id: 'tt0112844',
    _score: 1,
    _source:
     { adult: 'False',
       belongs_to_collection: '',
       budget: '0',
       genres: [Array],
       homepage: '',
       id: '47449',
       imdb_id: 'tt0112844',
       original_language: 'en',
       original_title: 'Denise Calls Up',
       overview:
        'A group of friends in New York, working away at their PCs and laptops, keep in touch exclusively by phone and fax. They are all too busy to meet face to face. Gale plays matchmaker, by phone, to Jerry and Barbara who, in turn, hit it off beautifully – via phone and fax. Martin gets a telephone call from someone he\'s never met. It\'s Denise, with some extraordinary news. Tapping away at his computer all the while, he develops a sort of friendship with Denise – via phone. And so it goes as the friends, tap, tap, tapping away, share news, hopes, and dreams – via phone and fax. Finally Gale has an unfortunate encounter with a phone, Denise has some more news for Martin, and Frank plans a gala New Year\'s Eve party, but will he answer the door?',
       popularity: '0.466476',
       poster_path: '/y3Jzrup1AARl8TBaQPbTR1FRnx8.jpg',
       production_companies: [Array],
       production_countries: [Array],
       release_date: '1995-05-17',
       revenue: 0,
       runtime: 80,
       spoken_languages: [Array],
       status: 'Released',
       tagline:
        'A hilarious heart-ringing fable about life, love and hangups.',
       title: 'Denise Calls Up',
       video: false,
       vote_average: 6.6,
       vote_count: 5,
       poster:
        'https://images-na.ssl-images-amazon.com/images/M/MV5BMTM5MTM1NjIxNV5BMl5BanBnXkFtZTcwMTc5OTkxMQ@@._V1_SX300.jpg',
       categories: 'Comedy',
       actors:
        'Tim Daly, Caroleen Feeney, Dan Gunther, Dana Wheeler-Nicholson',
       director: 'Hal Salwen',
       language: 'English',
       production: 'Sony Pictures Home Entertainment' } },
  { _index: 'movies',
    _type: 'all',
    _id: 'tt0113122',
    _score: 1,
    _source:
     { adult: 'False',
       belongs_to_collection: '',
       budget: '0',
       genres: [Array],
       homepage: '',
       id: '40926',
       imdb_id: 'tt0113122',
       original_language: 'en',
       original_title: 'Frisk',
       overview:
        'A first person narrative of a gay serial killer explores violence, sexuality, and imagination.',
       popularity: '0.319215',
       poster_path: '/q1qI7bxOUMUPxUUALkTjXa1EiCP.jpg',
       production_companies: [],
       production_countries: [Array],
       release_date: '1996-03-22',
       revenue: 0,
       runtime: 88,
       spoken_languages: [Array],
       status: 'Released',
       tagline: '',
       title: 'Frisk',
       video: false,
       vote_average: 3,
       vote_count: 3,
       poster:
        'https://m.media-amazon.com/images/M/MV5BMTkxMjQzMzMxN15BMl5BanBnXkFtZTcwODc0OTgyMQ@@._V1_SX300.jpg',
       categories: 'Drama, Thriller',
       actors:
        'Michael Gunther, Craig Chester, Michael Stock, Raoul O\'Connell',
       director: 'Todd Verow',
       language: 'English',
       production: 'Strand Releasing' } },
  { _index: 'movies',
    _type: 'all',
    _id: 'tt0112701',
    _score: 1,
    _source:
     { adult: 'False',
       belongs_to_collection: '',
       budget: '0',
       genres: [Array],
       homepage: '',
       id: '32513',
       imdb_id: 'tt0112701',
       original_language: 'en',
       original_title: 'Cold Comfort Farm',
       overview:
        'In this adaptation of the satirical British novel, Flora Poste, a plucky London society girl orphaned at age 19, finds a new home with some rough relatives,
the Starkadders of Cold Comfort Farm. With a take-charge attitude and some encouragement from her mischievous friend, Mary, Flora changes the Starkadders\' lives forever when she settles into their rustic estate, bringing the backward clan up to date and finding inspiration for her novel in the process.',
       popularity: '1.92386',
       poster_path: '/8kVQkrbrhfpkdZgYH5efOB8t6yK.jpg',
       production_companies: [],
       production_countries: [Array],
       release_date: '1995-01-01',
       revenue: 0,
       runtime: 95,
       spoken_languages: [Array],
       status: 'Released',
       tagline:
        'She discovered a new branch of her family tree... the one with all the nuts.',
       title: 'Cold Comfort Farm',
       video: false,
       vote_average: 7,
       vote_count: 21,
       poster:
        'https://m.media-amazon.com/images/M/MV5BZWI3MTA3NGEtYTg4ZC00MzgwLTliMGQtMjU2MWM5MmVmYThhXkEyXkFqcGdeQXVyNzc5MjA3OA@@._V1_SX300.jpg',
       categories: 'Comedy, Romance',
       actors:
        'Eileen Atkins, Kate Beckinsale, Sheila Burrell, Stephen Fry',
       director: 'John Schlesinger',
       language: 'English',
       production: 'Universal Pictures' } },
  { _index: 'movies',
    _type: 'all',
    _id: 'tt0108333',
    _score: 1,
    _source:
     { adult: 'False',
       belongs_to_collection: '',
       budget: '30000000',
       genres: [Array],
       homepage: 'http://movies.disney.com/the-three-musketeers',
       id: '10057',
       imdb_id: 'tt0108333',
       original_language: 'en',
       original_title: 'The Three Musketeers',
       overview:
        'D\'Artagnan travels to Paris hoping to become a musketeer, one of the French king\'s elite bodyguards, only to discover that the corps has been disbanded by
conniving Cardinal Richelieu, who secretly hopes to usurp the throne. Fortunately, Athos, Porthos and Aramis have refused to lay down their weapons and continue to protect their king. D\'Artagnan joins with the rogues to expose Richelieu\'s plot against the crown.',
       popularity: '6.34785',
       poster_path: '/cQsjMRId7r61Nh0bwEtGzCvp9gS.jpg',
       production_companies: [Array],
       production_countries: [Array],
       release_date: '1993-11-11',
       revenue: 53898845,
       runtime: 105,
       spoken_languages: [Array],
       status: 'Released',
       tagline: 'All for one and one for all!',
       title: 'The Three Musketeers',
       video: false,
       vote_average: 6.2,
       vote_count: 219,
       poster:
        'https://m.media-amazon.com/images/M/MV5BMzc4OTJlMTgtMWE5MC00MDRlLWE2MDQtYTI4ZTAzNzUyZjM2XkEyXkFqcGdeQXVyNjExODE1MDc@._V1_SX300.jpg',
       categories: 'Action, Adventure, Comedy, Family, Romance',
       actors:
        'Charlie Sheen, Kiefer Sutherland, Chris O\'Donnell, Oliver Platt',
       director: 'Stephen Herek',
       language: 'English',
       production: 'Disney' } },
  { _index: 'movies',
    _type: 'all',
    _id: 'tt0116095',
    _score: 1,
    _source:
     { adult: 'False',
       belongs_to_collection: '',
       budget: '0',
       genres: [Array],
       homepage: '',
       id: '10988',
       imdb_id: 'tt0116095',
       original_language: 'en',
       original_title: 'Diabolique',
       overview:
        'The wife and mistress of a cruel school master collaborate in a carefully planned and executed attempt to murder him. The plan goes well until the body, which has been strategically dumped, disappears. The strain starts to tell on the two women as a retired police investigator who is looking into the disappearance on a whim begins to think that they know more than they are telling, and their mental state is not helped when their victim is seen, apparently alive and well by one of the
pupils.',
       popularity: '4.530079',
       poster_path: '/woBHA1Obn53zziO6h0N9340SGMv.jpg',
       production_companies: [Array],
       production_countries: [Array],
       release_date: '1996-03-22',
       revenue: 0,
       runtime: 107,
       spoken_languages: [Array],
       status: 'Released',
       tagline: 'Two women. One man. The combination can be murder.',
       title: 'Diabolique',
       video: false,
       vote_average: 5.4,
       vote_count: 74,
       poster:
        'https://m.media-amazon.com/images/M/MV5BNmFmOWRkZWEtYWZlNC00MDQyLWFlODAtODdjNzU5MzY5ZGE3XkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg',
       categories: 'Drama, Horror, Mystery, Thriller',
       actors:
        'Sharon Stone, Isabelle Adjani, Chazz Palminteri, Kathy Bates',
       director: 'Jeremiah S. Chechik',
       language: 'English, Spanish',
       production: 'Warner Home Video' } },
  { _index: 'movies',
    _type: 'all',
    _id: 'tt0116508',
    _score: 1,
    _source:
     { adult: 'False',
       belongs_to_collection: '',
       budget: '25000000',
       genres: [Array],
       homepage: '',
       id: '36915',
       imdb_id: 'tt0116508',
       original_language: 'en',
       original_title: 'Heaven\'s Prisoners',
       overview:
        'A hardened New Orleans cop, Dave Robicheaux, finally tosses in the badge and settles into life on the bayou with his wife. But a bizarre plane crash draws him back into the fray when his family is viciously threatened.',
       popularity: '9.264679',
       poster_path: '/tJ61l57S7iMiHgzZJHehpfxjt2V.jpg',
       production_companies: [Array],
       production_countries: [Array],
       release_date: '1996-05-17',
       revenue: 0,
       runtime: 132,
       spoken_languages: [Array],
       status: 'Released',
       tagline:
        'For an ex-cop obsessed with an unsolved murder, trusting the wrong woman could be a deadly choice.',
       title: 'Heaven\'s Prisoners',
       video: false,
       vote_average: 5,
       vote_count: 17,
       poster:
        'https://m.media-amazon.com/images/M/MV5BMTYxMDcyNzA4N15BMl5BanBnXkFtZTcwODA0OTQxMQ@@._V1_SX300.jpg',
       categories: 'Drama, Mystery, Thriller',
       actors:
        'Alec Baldwin, Kelly Lynch, Mary Stuart Masterson, Eric Roberts',
       director: 'Phil Joanou',
       language: 'English',
       production: 'New Line Home Entertainment' } },
  { _index: 'movies',
    _type: 'all',
    _id: 'tt0106408',
    _score: 1,
    _source:
     { adult: 'False',
       belongs_to_collection: '',
       budget: '0',
       genres: [Array],
       homepage: '',
       id: '14587',
       imdb_id: 'tt0106408',
       original_language: 'en',
       original_title: 'Bhaji on the Beach',
       overview:
        'A group of women of Indian descent take a trip together from their home in Birmingham, England to the beach resort of Blackpool.',
       popularity: '0.441585',
       poster_path: '/zX5SNsEByf7YgPqyliI5xBjVgnc.jpg',
       production_companies: [Array],
       production_countries: [Array],
       release_date: '1994-01-21',
       revenue: 0,
       runtime: 100,
       spoken_languages: [Array],
       status: 'Released',
       tagline: '',
       title: 'Bhaji on the Beach',
       video: false,
       vote_average: 5.1,
       vote_count: 10,
       poster:
        'https://m.media-amazon.com/images/M/MV5BMTYyNTM0Mzk3MF5BMl5BanBnXkFtZTcwNDAzMTgxMQ@@._V1_SX300.jpg',
       categories: 'Comedy, Drama',
       actors:
        'Kim Vithana, Jimmi Harkishin, Sarita Khajuria, Akbar Kurtha',
       director: 'Gurinder Chadha',
       language: 'English, Punjabi',
       production: 'Sony Pictures Home Entertainment' } },
  { _index: 'movies',
    _type: 'all',
    _id: 'tt0117688',
    _score: 1,
    _source:
     { adult: 'False',
       belongs_to_collection: '',
       budget: '0',
       genres: [Array],
       homepage: '',
       id: '29621',
       imdb_id: 'tt0117688',
       original_language: 'en',
       original_title: 'Solo',
       overview:
        'An android fighting-machine (Mario Van Peebles) is charged with destroying a small brigade of rebels in a Latin American war who are fighting to maintain their freedom and protect their village. Contrary to his programming, Peebles decides to stay and assist the rebels in their plight. Having gained this information, his
"creators" develop a more powerful android to try and defeat him.',
       popularity: '1.899069',
       poster_path: '/qYKL8PCgQhZaGbyNJ7nWH0Tloy4.jpg',
       production_companies: [Array],
       production_countries: [Array],
       release_date: '1996-10-23',
       revenue: 0,
       runtime: 94,
       spoken_languages: [Array],
       status: 'Released',
       tagline: 'Part man. Part machine. Total weapon.',
       title: 'Solo',
       video: false,
       vote_average: 3.9,
       vote_count: 18,
       poster:
        'https://m.media-amazon.com/images/M/MV5BNzI1NDIyMDc1Ml5BMl5BanBnXkFtZTcwNjU2ODMyMQ@@._V1_SX300.jpg',
       categories: 'Action, Sci-Fi, Thriller',
       actors:
        'Mario Van Peebles, Barry Corbin, William Sadler, Jaime Gomez',
       director: 'Norberto Barba',
       language: 'English, Spanish',
       production: 'Sony Pictures Home Entertainment' } },
  { _index: 'movies',
    _type: 'all',
    _id: 'tt0104046',
    _score: 1,
    _source:
     { adult: 'False',
       belongs_to_collection: '',
       budget: '0',
       genres: [Array],
       homepage: '',
       id: '44103',
       imdb_id: 'tt0104046',
       original_language: 'nl',
       original_title: 'Daens',
       overview:
        'In the 1890s, Father Adolf Daens goes to Aalst, a textile town where child labor is rife, pay and working conditions are horrible, the poor have no vote, and the Catholic church backs the petite bourgeoisie in oppressing workers. He writes a few columns for the Catholic paper, and soon workers are listening and the powerful are in an uproar. He\'s expelled from the Catholic party, so he starts the Christian Democrats and is elected to Parliament. After Rome disciplines him, he must choose between two callings, as priest and as champion of workers. In subplots, a courageous young woman falls in love with a socialist and survives a shop foreman\'s rape; children die; prelates play billiards.',
       popularity: '0.755047',
       poster_path: '/4fS6fxlj8drUKI17eBsDIm9mfF8.jpg',
       production_companies: [Array],
       production_countries: [Array],
       release_date: '1992-09-01',
       revenue: 0,
       runtime: 138,
       spoken_languages: [Array],
       status: 'Released',
       tagline: '',
       title: 'Priest Daens',
       video: false,
       vote_average: 6.7,
       vote_count: 15,
       poster:
        'https://images-na.ssl-images-amazon.com/images/M/MV5BMTUxNTgzOTE1OV5BMl5BanBnXkFtZTcwNDI3MzIyMQ@@._V1_SX300.jpg',
       categories: 'Biography, Drama, History',
       actors: 'Jan Decleir, Gérard Desarthe, Antje de Boeck, Michael Pas',
       director: 'Stijn Coninx',
       language: 'Flemish, Dutch, French, Latin, Spanish',
       production: 'Favourite Films' } },
  { _index: 'movies',
    _type: 'all',
    _id: 'tt0109028',
    _score: 1,
    _source:
     { adult: 'False',
       belongs_to_collection: '',
       budget: '0',
       genres: [Array],
       homepage: '',
       id: '68445',
       imdb_id: 'tt0109028',
       original_language: 'de',
       original_title: 'Á köldum klaka',
       overview:
        'A Japanese businessman travels to Iceland and has a series of misadventures while venturing to a remote area to perform a traditional burial ritual where his parents died several years back.',
       popularity: '0.494977',
       poster_path: '/4aytLuIicECojFIJCqaLk1fj1rf.jpg',
       production_companies: [Array],
       production_countries: [Array],
       release_date: '1995-02-10',
       revenue: 0,
       runtime: 85,
       spoken_languages: [Array],
       status: 'Released',
       tagline: '',
       title: 'Cold Fever',
       video: false,
       vote_average: 7.7,
       vote_count: 6,
       poster:
        'http://ia.media-imdb.com/images/M/MV5BMTMxNTk1NTEwMF5BMl5BanBnXkFtZTcwNzg4ODUyMQ@@._V1_SX300.jpg',
       categories: 'Comedy, Drama, Mystery',
       actors:
        'Masatoshi Nagase, Lili Taylor, Fisher Stevens, Gísli Halldórsson',
       director: 'Friðrik Þór Friðriksson',
       language: 'English, Icelandic, Japanese, German',
       production: 'Icicle Films' } },
  { _index: 'movies',
    _type: 'all',
    _id: 'tt0108255',
    _score: 1,
    _source:
     { adult: 'False',
       belongs_to_collection: '',
       budget: '48000000',
       genres: [Array],
       homepage: '',
       id: '9607',
       imdb_id: 'tt0108255',
       original_language: 'en',
       original_title: 'Super Mario Bros.',
       overview:
        'Mario and Luigi, plumbers from Brooklyn, find themselves in an alternate universe where evolved dinosaurs live in hi-tech squalor. They\'re the only hope to
save our universe from invasion by the dino dictator, Koopa.',
       popularity: '7.198455',
       poster_path: '/bmv7fmcBFzjnJvirfAdZm75qERY.jpg',
       production_companies: [Array],
       production_countries: [Array],
       release_date: '1993-05-28',
       revenue: 20915465,
       runtime: 104,
       spoken_languages: [Array],
       status: 'Released',
       tagline: 'This Ain\'t No Game.',
       title: 'Super Mario Bros.',
       video: false,
       vote_average: 4,
       vote_count: 236,
       poster:
        'https://m.media-amazon.com/images/M/MV5BMzRmNGY0NTctYTNkNC00M2FkLWI0ZTgtYTE5ODhiZjYxMDkxXkEyXkFqcGdeQXVyNjE5MjUyOTM@._V1_SX300.jpg',
       categories: 'Adventure, Comedy, Family, Fantasy, Sci-Fi',
       actors:
        'Bob Hoskins, John Leguizamo, Dennis Hopper, Samantha Mathis',
       director: 'Annabel Jankel, Rocky Morton',
       language: 'English',
       production: 'Buena Vista' } } ]