const client = require("../../connection/connection");
/**A multi-value metrics aggregation that computes stats over numeric values extracted from the aggregated documents. These values can be extracted either from specific numeric fields in the documents, or be generated by a provided script.  */
client
  .search({
    index: "movies",
    type: "all",
    body: {
      query: {
        match_all: {}
      },
      size: 0,
      aggs: {
        budget_stats: {
          stats: {
            field: "budget"
          }
        }
      }
    }
  })
  .then(response => console.log(response.aggregations.budget_stats))
  .catch(error => console.log(error));
